--- 	
- name: Install insecure FTP server as long as not in production 	
  hosts: all 	
  become: yes 	
  tasks: 	
  - name: Install FTP server if not in production 	
    yum: 	
      name: vsftpd 	
      state: latest 	
    when: 
    - ansible_facts['distribution'] == "CentOS"
    - stage != "prod"
