---
- name: demo loop
  hosts: centos
  become: yes
  vars:
    services:
    - httpd
    - sshd  
  tasks:
  - name: check if service is started
    systemd:
      name: "{{item}}"
      state: started
    loop: "{{services}}"
